[pytest]
testpaths = tests/step_defs
python_files = test_*.py
bdd_features_base_dir = tests/features

markers =
    smoke: Smoke tests
    services: Service discovery tests
    sample_test: Sample test
    second_sample_test: Second sample test
    third: Third test

addopts = -v --tb=short

